### ISSUE TITLE
Forks and maintainership

### ISSUE THREAD

**Issue by ajlennon** [resin-io-playground/resin-octoprint#17]
Hi folks. I have a fork here which I'm maintaining on and off with a focus on keeping my Creality 3D printers working.

https://github.com/DynamicDevices/octobalena

I know you're looking for people to take on maintainership of some of these balenalabs / open fleets projects and this is something aligned with my interests that I might be able to help with.

Let me know!

A/

**Comment by chrisys** [comment]
@ajlennon very interested for sure! The reason why I updated this one is because I didn't have a use for any of the other stuff Octobalena adds, and I think it was broken at the time as well. I'll give yours a go again; I don't have a screen plugged in so don't strictly need octodash but I can't see that it would cause any issue having it there.
